# Generated by Django 5.1.6 on 2025-03-25 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllAdmin',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_name', models.CharField(max_length=150)),
                ('mail', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('admin_type', models.CharField(choices=[('SYS_ADMIN', 'Administrateur'), ('SUPER_ADMIN', 'Super Admin')], default='SYS_ADMIN', max_length=20)),
                ('state', models.CharField(choices=[('VISIBLE', 'Visible'), ('DELETE', 'Delete')], default='VISIBLE', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'AllAdmin',
                'verbose_name_plural': 'AllAdmins',
            },
        ),
    ]
