# Generated by Django 5.1.6 on 2025-02-26 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alladmin',
            name='country_calling_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='alladmin',
            name='localite',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
