# Generated by Django 5.1.6 on 2025-03-25 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_admin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alladmin',
            name='state',
        ),
        migrations.AddField(
            model_name='alladmin',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alladmin',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alladmin',
            name='country_calling_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='alladmin',
            name='localite',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alladmin',
            name='tel_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
