# Generated by Django 5.1.6 on 2025-02-26 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_admin', '0002_alladmin_country_calling_code_alladmin_localite'),
    ]

    operations = [
        migrations.AddField(
            model_name='alladmin',
            name='password',
            field=models.CharField(blank=True, default='pbkdf2_sha256$870000$Tp69Mn34TWbkdAGUjWipXg$xFf97HU/eHIx7MPHVC3FfXtVnh8QZhVUXBE8oO1X8ak=', max_length=128, null=True),
        ),
    ]
