# Generated by Django 5.1.6 on 2025-03-25 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agence', '0001_initial'),
        ('sys_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authorisation',
            fields=[
                ('authorisation_id', models.AutoField(primary_key=True, serialize=False)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorisations', to='agence.agency')),
                ('sys_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorisations', to='sys_admin.sysadmin')),
            ],
            options={
                'verbose_name': 'Authorisation',
                'verbose_name_plural': 'Authorisations',
                'unique_together': {('sys_admin', 'agency')},
            },
        ),
    ]
