# Generated by Django 5.1.6 on 2025-03-25 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('driver_id', models.AutoField(primary_key=True, serialize=False)),
                ('driver_name', models.CharField(max_length=100)),
                ('country_calling_code', models.CharField(blank=True, max_length=5, null=True)),
                ('Tel_number', models.CharField(max_length=15)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('localite', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(choices=[('VISIBLE', 'Visible'), ('DELETE', 'Delete')], default='VISIBLE', max_length=10)),
            ],
            options={
                'verbose_name': 'Driver',
                'verbose_name_plural': 'Drivers',
            },
        ),
    ]
