# Generated by Django 5.1.6 on 2025-02-25 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chauffeur', '0002_driver_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
