# Generated by Django 5.1.6 on 2025-02-26 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chauffeur', '0004_remove_driver_address_driver_city_driver_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='country_calling_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
