# Generated by Django 5.1.6 on 2025-03-25 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperAdmin',
            fields=[
                ('superadmin_id', models.AutoField(primary_key=True, serialize=False)),
                ('rank', models.PositiveIntegerField(default=1, help_text="Niveau hiérarchique de l'admin")),
                ('state', models.CharField(choices=[('VISIBLE', 'Visible'), ('DELETE', 'Delete')], default='VISIBLE', max_length=10)),
                ('all_admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SuperAdmin',
                'verbose_name_plural': 'SuperAdmins',
            },
        ),
    ]
