# Generated by Django 5.1.6 on 2025-02-24 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SuperAdmin',
            fields=[
                ('superadmin_id', models.AutoField(primary_key=True, serialize=False)),
                ('superadmin_name', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'SuperAdmin',
                'verbose_name_plural': 'SuperAdmins',
            },
        ),
    ]
