# Generated by Django 5.1.6 on 2025-02-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='superadmin',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='superadmin',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='superadmin',
            name='mail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='superadmin',
            name='rank',
            field=models.PositiveIntegerField(default=1, help_text="Niveau hiérarchique de l'admin"),
        ),
        migrations.AddField(
            model_name='superadmin',
            name='tel_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
