# Generated by Django 5.1.6 on 2025-02-24 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_admin', '0001_initial'),
        ('superadmin', '0002_superadmin_city_superadmin_country_superadmin_mail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='superadmin',
            name='city',
        ),
        migrations.RemoveField(
            model_name='superadmin',
            name='country',
        ),
        migrations.RemoveField(
            model_name='superadmin',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='superadmin',
            name='superadmin_name',
        ),
        migrations.RemoveField(
            model_name='superadmin',
            name='tel_number',
        ),
        migrations.AddField(
            model_name='superadmin',
            name='all_admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='all_admin.alladmin'),
        ),
        migrations.AddField(
            model_name='superadmin',
            name='state',
            field=models.CharField(choices=[('VISIBLE', 'Visible'), ('DELETE', 'Delete')], default='VISIBLE', max_length=10),
        ),
    ]
