# Generated by Django 5.1.6 on 2025-02-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agence', '0002_agency_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency',
            name='agency_city',
        ),
        migrations.AddField(
            model_name='agency',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='localite',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='agency',
            name='agency_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='agency',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
