# Generated by Django 5.1.6 on 2025-02-24 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ville_traversee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('line_id', models.AutoField(primary_key=True, serialize=False)),
                ('arrival_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_lines', to='ville_traversee.citycrossline')),
                ('starting_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starting_lines', to='ville_traversee.citycrossline')),
            ],
            options={
                'verbose_name': 'Line',
                'verbose_name_plural': 'Lines',
            },
        ),
    ]
