# Generated by Django 5.1.6 on 2025-02-24 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ligne', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='state',
            field=models.CharField(choices=[('VISIBLE', 'Visible'), ('DELETE', 'Delete')], default='VISIBLE', max_length=10),
        ),
    ]
