# Generated by Django 5.1.6 on 2025-03-25 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service_vehicule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicule_id', models.AutoField(primary_key=True, serialize=False)),
                ('Vehicule_number', models.CharField(max_length=50, unique=True)),
                ('licence_plate', models.CharField(max_length=20, unique=True)),
                ('owner', models.CharField(max_length=100)),
                ('capacity', models.PositiveIntegerField()),
                ('purchase_date', models.DateField()),
                ('vehicule_state', models.CharField(choices=[('USED', 'Used'), ('UNDER_MAINTENANCE', 'Under Maintenance'), ('OUT_OF_SERVICE', 'Out of Service')], max_length=20)),
                ('vehicule_type', models.CharField(choices=[('BUS', 'Bus'), ('CAR', 'Car'), ('VAN', 'Van'), ('TRUCK', 'Truck'), ('MOTORCYCLE', 'Motorcycle')], max_length=20)),
                ('state', models.CharField(choices=[('VISIBLE', 'Visible'), ('DELETE', 'Delete')], default='VISIBLE', max_length=10)),
                ('service_available', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_vehicule.serviceavailable')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
            },
        ),
    ]
