# Generated by Django 5.1.6 on 2025-02-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sysadmin',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sysadmin',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
