# Generated by Django 5.1.6 on 2025-02-24 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agence', '0002_agency_state'),
        ('all_admin', '0001_initial'),
        ('sys_admin', '0002_sysadmin_city_sysadmin_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sysadmin',
            name='Tel_number',
        ),
        migrations.RemoveField(
            model_name='sysadmin',
            name='admin_name',
        ),
        migrations.RemoveField(
            model_name='sysadmin',
            name='city',
        ),
        migrations.RemoveField(
            model_name='sysadmin',
            name='country',
        ),
        migrations.RemoveField(
            model_name='sysadmin',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='sysadmin',
            name='super_admin',
        ),
        migrations.AddField(
            model_name='sysadmin',
            name='all_admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='all_admin.alladmin'),
        ),
        migrations.AddField(
            model_name='sysadmin',
            name='state',
            field=models.CharField(choices=[('VISIBLE', 'Visible'), ('DELETE', 'Delete')], default='VISIBLE', max_length=10),
        ),
        migrations.AlterField(
            model_name='sysadmin',
            name='authorised_agencies',
            field=models.ManyToManyField(related_name='sysadmins', to='agence.agency'),
        ),
    ]
